### ISSUE TITLE
new user can't addd plz check bro

### ISSUE THREAD

**Issue by sahilkashid1024** [sanjoyksaha/library_management_system#1]
Fatal error: Uncaught mysqli_sql_exception: Unknown column 'department' in 'field list' in C:\xampp\htdocs\library_management_system-master\student\include\registerfunction.php:58 Stack trace: #0 C:\xampp\htdocs\library_management_system-master\student\include\registerfunction.php(58): mysqli_query(Object(mysqli), 'INSERT INTO `st...') #1 C:\xampp\htdocs\library_management_system-master\student\registration.php(3): include('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\library_management_system-master\student\include\registerfunction.php on line 58

**Comment by sanjoyksaha** [comment]
Please add a 'department' column with an integer data type and a length of 6 to your 'students' table.
